imports:
    - php

filter:
    excluded_paths: [vendor1/*, tests/*]

build:
    image: default-bionic
    
    dependencies:
        override:
            - true
            
    nodes:
        my-tests:
            environment:
                php:
                    # version: 8.1.13
                    # version: 8.1.17
                    version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    
    tests:
        override:
              - command: "XDEBUG_MODE=coverage vendor1/bin/phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"

